- name: Install PostgreSQL on Ubuntu
  apt:
    name: postgresql
    state: present
  when: ansible_os_family == "Debian"

- name: Install PostgreSQL on macOS
  homebrew:
    name: postgresql
    state: present
  when: ansible_os_family == "Darwin"

- name: Ensure PostgreSQL is running on Ubuntu
  service:
    name: postgresql
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"

- name: Ensure PostgreSQL is running on macOS
  shell: brew services start postgresql
  when: ansible_os_family == "Darwin"

- name: Install PostgreSQL dependencies for Ansible
  pip:
    name:
      - psycopg2-binary
  when: ansible_os_family == "Debian"

- name: Create PostgreSQL database (Ubuntu)
  become_user: postgres
  community.postgresql.postgresql_db:
    name: my_database
    state: present
  when: ansible_os_family == "Debian"

- name: Create PostgreSQL database (macOS)
  shell: createdb my_database
  when: ansible_os_family == "Darwin"

- name: Create PostgreSQL user (Ubuntu)
  become_user: postgres
  community.postgresql.postgresql_user:
    db: my_database
    name: my_user
    password: my_password
    priv: "ALL"
    state: present
  when: ansible_os_family == "Debian"

- name: Create PostgreSQL user (macOS)
  shell: psql -d my_database -c "CREATE USER my_user WITH PASSWORD 'my_password'; GRANT ALL PRIVILEGES ON DATABASE my_database TO my_user;"
  when: ansible_os_family == "Darwin"
