- name: Install NVM (Linux & macOS)
  shell: >
    curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
  args:
    creates: "{{ '~/.nvm' if ansible_os_family == 'Darwin' else '/root/.nvm' }}"

- name: Load NVM and install latest Node.js
  shell: |
    export NVM_DIR="{{ '~/.nvm' if ansible_os_family == 'Darwin' else '/root/.nvm' }}"
    source $NVM_DIR/nvm.sh
    nvm install node
    nvm alias default node
  args:
    executable: /bin/bash
